development:
  adapter: mysql
  database: amatos_dev
  username: root
  password: password
  socket: /tmp/mysql.sock  

test: 
  adapter: mysql
  database: amatos_test
  username: root
  password: password
  socket: /tmp/mysql.sock

production: 
  adapter: mysql
  database: amatos_pro
  username: root
  password: password
  socket: /tmp/mysql.sock

